<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-DQ5N2O9I" failures="1" tests="4" name="Retry Multiple Failed Test" time="0.161" errors="0" timestamp="2022-01-14T17:40:37 IST">
  <testcase classname="com.myTests.myTest" name="Test2" time="0.02">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.myTests.myTest" name="Test2" time="0.013">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.myTests.myTest" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="com.myTests.myTest" name="Test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.myTests.myTest.Test2(myTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Retry Multiple Failed Test -->
